//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Helper.Dataaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.BusSeatInfos = new HashSet<BusSeatInfo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string CID { get; set; }
        public string Description { get; set; }
        public decimal SeatRent { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime Time { get; set; }
        public int DepPlace { get; set; }
        public int DestPlace { get; set; }
        public byte Status { get; set; }
    
        public virtual BusCompany BusCompany { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusSeatInfo> BusSeatInfos { get; set; }
    }
}
