//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Helper.Dataaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusSeatInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusSeatInfo()
        {
            this.SeatBookingInfos = new HashSet<SeatBookingInfo>();
        }
    
        public int ID { get; set; }
        public string SID { get; set; }
        public int BusID { get; set; }
        public byte Status { get; set; }
    
        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatBookingInfo> SeatBookingInfos { get; set; }
    }
}
