//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Helper.Dataaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoomInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelRoomInfo()
        {
            this.hotelBookingInfos = new HashSet<hotelBookingInfo>();
        }
    
        public int ID { get; set; }
        public string RID { get; set; }
        public int HotelId { get; set; }
        public string RoomType { get; set; }
        public int Rent { get; set; }
        public string Description { get; set; }
        public byte Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hotelBookingInfo> hotelBookingInfos { get; set; }
    }
}
