//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Helper.Dataaccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class hotelBookingInfo
    {
        public int BID { get; set; }
        [Required(ErrorMessage = "Customer ID is required")]
        public int CustomerId { get; set; }
        [Required(ErrorMessage = "Booking Dates required")]
        public System.DateTime BookingDate { get; set; }
        [Required(ErrorMessage = "Status is required")]
        public byte status { get; set; }
        [Required(ErrorMessage = "RoomID is required")]
        public int RoomId { get; set; }
    
        public virtual HotelRoomInfo HotelRoomInfo { get; set; }
        public virtual User User { get; set; }
    }
}
